openapi: 3.1.0
info:
  version: 1.0.0
  title: MFP API
paths:
  # BANNERS
  /banners/{bannerId}:
    get:
      summary: Get current banner
      operationId: getBanner
      tags:
        - banners
      parameters:
        - name: bannerId
          in: path
          required: true
          description: The id of the banner to get # note: our app only uses one id
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  $metadata: #note: should not be in the response
                    type: object
                    properties:
                      httpStatusCode:
                        type: integer
                      requestId:
                        type: string
                      attempts:
                        type: integer
                      totalRetryDelay:
                        type: integer
                  Item: #note: rename to "banner" for clarity
                    type: object
                    properties:
                      createdAt:
                        type: integer
                      endDate:
                        type: integer
                      lastAltered:
                        type: integer
                      description:
                        type: string
                      title:
                        type: string
                      startDate:
                        type: integer
    post:
      summary: Create a banner
      operationId: createBanner
      tags:
        - banners
      parameters:
        - name: bannerId
          in: path
          required: true
          description: The id of the banner to get # note: our app only uses one id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Banner"
        required: true
      responses:
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  TableName: string # note: remove
                  Item: # note: rename to "banner" for clarity
                    type: object
                    properties:
                      key:
                        type: string
                      createdAt:
                        type: integer
                      endDate:
                        type: integer
                      lastAltered:
                        type: integer
                      description:
                        type: string
                      title:
                        type: string
                      startDate:
                        type: integer
        # {
        #    "TableName": "local-banners",
        #    "Item": {
        #        "key": "admin-banner-id",
        #        "createdAt": 1721663673026,
        #        "lastAltered": 1721663673026,
        #        "title": "aoijef;oaiwje",
        #        "description": "laiojewf;iajwe;",
        #        "link": "https://calendar.google.com/calendar/u/0/r",
        #        "startDate": 944974800000,
        #        "endDate": 1580705999000
        #    }
        # }
    delete:
      summary: Delete a banner
      operationId: createPets
      tags:
        - pets
      parameters:
        - name: bannerId
          in: path
          required: true
          description: The id of the banner to get # note: our app only uses one id
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  TableName: # note: remove
                    type: string
                  Key:
                    type: object
                    properties:
                      key:
                        type: string
        "403":
          description: Unauthorized
          # TODO: add more
        # {"TableName":"local-banners","Key":{"key":"admin-banner-id"}}
  # REPORTS
  /reports/{reportType}/{state}:
    post:
      summary: Create report
      operationId: createReport
      tags:
        - reports
      parameters:
        - name: reportType
          in: path
          required: true
          description: The report type # WP or SAR
          schema:
            type: string
        - name: state
          in: path
          required: true
          description: The state abbreviation # e.g. AL, OK, WY
          schema:
            type: string

# use as
  # schema:
  #   $ref: '#/components/schemas/Banner'
components:
  schemas:
    Banner:
      type: object
      required:
        - title
        - description
        - startDate
        - endDate
      properties:
        key:
          type: string
        createdAt: # this only shows up in the response so we may consider removing this
          type: integer
        endDate:
          type: integer
        lastAltered: # this only shows up in the response so we may consider removing this
          type: integer
        description:
          type: string
        title:
          type: string
        startDate:
          type: integer
        link:
          type: string


# 1. schema
# 1a. links
# 2. post response code
# 3. error responses
