# Refer to the README.md file in within this service directory to configure all ssm parameters required for this service.
service: app-api

frameworkVersion: "3"

package:
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-associate-waf
  - serverless-stack-termination-protection
  - serverless-iam-helper
  - serverless-s3-bucket-helper
  - serverless-api-client-certificate
  - serverless-offline
  - "@enterprise-cmcs/serverless-waf-plugin"

s3BucketHelper:
  loggingConfiguration:
    destinationBucketName: ${env:LOGGING_BUCKET, ssm:/configuration/${self:custom.stage}/s3/accessLogsBucket, ssm:/configuration/default/s3/accessLogsBucket}
    logFilePrefix: ${env:LOGGING_BUCKET, ssm:/configuration/${self:custom.stage}/s3/accessLogsPrefix, ssm:/configuration/default/s3/accessLogsPrefix}

custom:
  project: "mfp"
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"
  stage: ${sls:stage}
  region: ${aws:region}
  wafPlugin:
    name: ${self:service}-${self:custom.stage}-webacl-waf
  wafExcludeRules:
    awsCommon:
      - "SizeRestrictions_BODY"
  serverlessTerminationProtection:
    stages:
      - main
      - val
      - production
  dotenv:
    path: ../../.env
  bannerTableName: ${env:BANNER_TABLE_NAME, param:BannerTableName}
  wpFormBucket: ${env:WP_FORM_BUCKET, param:WpFormBucketName}
  wpReportTableName: ${env:WP_REPORT_TABLE_NAME, param:WpReportTableName}
  wpReportTableStreamArn: ${env:WP_REPORT_TABLE_STREAM_ARN, param:WpReportTableStreamArn}
  formTemplateTableName: ${env:FORM_TEMPLATE_TABLE_NAME, param:FormTemplateTableName}
  sarFormBucket: ${env:SAR_FORM_BUCKET, param:SarFormBucketName}
  sarReportTableName: ${env:SAR_REPORT_TABLE_NAME, param:SarReportTableName}
  sarReportTableStreamArn: ${env:SAR_REPORT_TABLE_STREAM_ARN, param:SarReportTableStreamArn}
  templateBucket: ${env:TEMPLATE_BUCKET, param:AttachmentsBucketName}
  webAclName: ${self:service}-${self:custom.stage}-webacl-waf
  associateWaf:
    name: ${self:custom.webAclName}
    version: V2
  bootstrapBrokerStringTls: ${env:BROKER_STRINGS, ssm:/configuration/${self:custom.stage}/bigmac/bootstrapBrokerStringTls, ssm:/configuration/default/bigmac/bootstrapBrokerStringTls}
  vpcId: ${env:VPC_ID, ssm:/configuration/${self:custom.stage}/vpc/id, ssm:/configuration/default/vpc/id}
  privateSubnets:
    - ${env:VPC_SUBNET_A, ssm:/configuration/${self:custom.stage}/vpc/subnets/private/a/id, ssm:/configuration/default/vpc/subnets/private/a/id}
    - ${env:VPC_SUBNET_B, ssm:/configuration/${self:custom.stage}/vpc/subnets/private/b/id, ssm:/configuration/default/vpc/subnets/private/b/id}
    - ${env:VPC_SUBNET_C, ssm:/configuration/${self:custom.stage}/vpc/subnets/private/c/id, ssm:/configuration/default/vpc/subnets/private/c/id}
  serverlessApiClientCertificate:
    rotateCerts: true
    daysLeft: 30
  authValue:
    main: aws_iam
    val: aws_iam
    production: aws_iam
params:
  main:
    topicNamespace: ""
  val:
    topicNamespace: ""
  production:
    topicNamespace: ""
  default:
    topicNamespace: --${self:custom.project}--${sls:stage}--
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  tracing:
    apiGateway: true
  logs:
    restApi: true
  iam:
    role:
      path: ${env:IAM_PATH, ssm:/configuration/${self:custom.stage}/iam/path, ssm:/configuration/default/iam/path, "/"}
      permissionsBoundary: ${env:IAM_PERMISSIONS_BOUNDARY, ssm:/configuration/${self:custom.stage}/iam/permissionsBoundaryPolicy, ssm:/configuration/default/iam/permissionsBoundaryPolicy, ""}
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
        - Effect: "Allow"
          Action:
            - ssm:GetParameter
          Resource: "*"
        - Effect: "Allow"
          Action:
            - execute-api:Invoke
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:ListBucket"
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::${self:custom.templateBucket}"
            - "arn:aws:s3:::${self:custom.templateBucket}/templates/*"
            - "arn:aws:s3:::${self:custom.wpFormBucket}"
            - "arn:aws:s3:::${self:custom.wpFormBucket}/formTemplates/*"
            - "arn:aws:s3:::${self:custom.wpFormBucket}/fieldData/*"
            - "arn:aws:s3:::${self:custom.sarFormBucket}"
            - "arn:aws:s3:::${self:custom.sarFormBucket}/formTemplates/*"
            - "arn:aws:s3:::${self:custom.sarFormBucket}/fieldData/*"
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeStream
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:ListShards
            - dynamodb:ListStreams
          Resource:
            - ${self:custom.wpReportTableStreamArn}
            - ${self:custom.sarReportTableStreamArn}
  environment:
    BANNER_TABLE_NAME: ${self:custom.bannerTableName}
    BOOTSTRAP_BROKER_STRING_TLS: ${self:custom.bootstrapBrokerStringTls}
    WP_REPORT_TABLE_NAME: ${self:custom.wpReportTableName}
    WP_FORM_BUCKET: ${self:custom.wpFormBucket}
    FORM_TEMPLATE_TABLE_NAME: ${self:custom.formTemplateTableName}
    SAR_REPORT_TABLE_NAME: ${self:custom.sarReportTableName}
    SAR_FORM_BUCKET: ${self:custom.sarFormBucket}
    STAGE: ${self:custom.stage}
    TEMPLATE_BUCKET: ${self:custom.templateBucket}

functions:
  createBanner:
    handler: handlers/banners/create.createBanner
    events:
      - http:
          path: banners/{bannerId}
          method: post
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                bannerId: true
  deleteBanner:
    handler: handlers/banners/delete.deleteBanner
    events:
      - http:
          path: banners/{bannerId}
          method: delete
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                bannerId: true
  fetchBanner:
    handler: handlers/banners/fetch.fetchBanner
    events:
      - http:
          path: banners/{bannerId}
          method: get
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                bannerId: true
  fetchTemplate:
    handler: handlers/templates/fetch.fetchTemplate
    events:
      - http:
          path: templates/{templateName}
          method: get
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                templateName: true
  archiveReport:
    handler: handlers/reports/archive.archiveReport
    events:
      - http:
          path: reports/archive/{reportType}/{state}/{id}
          method: put
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                reportType: true
                state: true
                id: true
  createReport:
    handler: handlers/reports/create.createReport
    events:
      - http:
          path: reports/{reportType}/{state}
          method: post
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                reportType: true
                state: true
  fetchReport:
    handler: handlers/reports/fetch.fetchReport
    events:
      - http:
          path: reports/{reportType}/{state}/{id}
          method: get
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                reportType: true
                state: true
                id: true
  fetchReportsByState:
    handler: handlers/reports/fetch.fetchReportsByState
    events:
      - http:
          path: reports/{reportType}/{state}
          method: get
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                reportType: true
                state: true
  releaseReport:
    handler: handlers/reports/release.releaseReport
    events:
      - http:
          path: reports/release/{reportType}/{state}/{id}
          method: put
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                state: true
                id: true
  submitReport:
    handler: handlers/reports/submit.submitReport
    timeout: 30
    memorySize: 2048
    events:
      - http:
          path: reports/submit/{reportType}/{state}/{id}
          method: post
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                reportType: true
                state: true
                id: true
  updateReport:
    handler: handlers/reports/update.updateReport
    timeout: 30
    memorySize: 2048
    events:
      - http:
          path: reports/{reportType}/{state}/{id}
          method: put
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                reportType: true
                state: true
                id: true
  approveReport:
    handler: handlers/reports/approve.approveReport
    timeout: 30
    memorySize: 2048
    events:
      - http:
          path: reports/approve/{reportType}/{state}/{id}
          method: put
          cors: true
          authorizer: ${self:custom.authValue.${self:custom.stage}, ""}
          request:
            parameters:
              paths:
                reportType: true
                state: true
                id: true
  postKafkaData:
    handler: handlers/kafka/post/postKafkaData.handler
    environment:
      BOOTSTRAP_BROKER_STRING_TLS: ${self:custom.bootstrapBrokerStringTls}
      STAGE: ${self:custom.stage}
      topicNamespace: ${param:topicNamespace}
    maximumRetryAttempts: 2
    timeout: 120
    memorySize: 2048
    vpc:
      securityGroupIds:
        - Ref: KafkaSecurityGroup
      subnetIds: ${self:custom.privateSubnets}
    events:
      - stream:
          type: dynamodb
          arn: ${self:custom.wpReportTableStreamArn}
          startingPosition: TRIM_HORIZON
          maximumRetryAttempts: 2
          enabled: true
      - stream:
          type: dynamodb
          arn: ${self:custom.sarReportTableStreamArn}
          startingPosition: TRIM_HORIZON
          maximumRetryAttempts: 2
          enabled: true
  postWpBucketData:
    handler: handlers/kafka/post/postKafkaData.handler
    environment:
      BOOTSTRAP_BROKER_STRING_TLS: ${self:custom.bootstrapBrokerStringTls}
      STAGE: ${self:custom.stage}
      topicNamespace: ${param:topicNamespace}
    maximumRetryAttempts: 2
    timeout: 120
    memorySize: 2048
    vpc:
      securityGroupIds:
        - Ref: KafkaSecurityGroup
      subnetIds: ${self:custom.privateSubnets}
    events:
      - s3:
          bucket: ${self:custom.wpFormBucket}
          existing: true
          forceDeploy: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: fieldData/
            - suffix: .json
      - s3:
          bucket: ${self:custom.wpFormBucket}
          existing: true
          forceDeploy: true
          event: s3:ObjectTagging:Put
          rules:
            - prefix: fieldData/
            - suffix: .json
  postSarBucketData:
    handler: handlers/kafka/post/postKafkaData.handler
    environment:
      BOOTSTRAP_BROKER_STRING_TLS: ${self:custom.bootstrapBrokerStringTls}
      STAGE: ${self:custom.stage}
      topicNamespace: ${param:topicNamespace}
    maximumRetryAttempts: 2
    timeout: 120
    memorySize: 2048
    vpc:
      securityGroupIds:
        - Ref: KafkaSecurityGroup
      subnetIds: ${self:custom.privateSubnets}
    events:
      - s3:
          bucket: ${self:custom.sarFormBucket}
          existing: true
          forceDeploy: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: fieldData/
            - suffix: .json
      - s3:
          bucket: ${self:custom.sarFormBucket}
          existing: true
          forceDeploy: true
          event: s3:ObjectTagging:Put
          rules:
            - prefix: fieldData/
            - suffix: .json
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId: !Ref ApiGatewayRestApi
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId: !Ref ApiGatewayRestApi
    KafkaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security Group for streaming functions.  Egress all is set by default.
        VpcId: ${self:custom.vpcId}
  Outputs:
    ApiGatewayRestApiName:
      Value: !Ref ApiGatewayRestApi
    ApiGatewayRestApiUrl:
      Value: !Sub https://${ApiGatewayRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:custom.stage}
    Region:
      Value: !Sub ${AWS::Region}
