import { SystemStyleObject } from "@chakra-ui/react";
import React from "react";
import {
  AnyObject,
  CustomHtmlElement,
  ReportRoute,
  ValidationType,
} from "types";

// FORM & FIELD STRUCTURE

/**
 * Reports can have entities which have their own data objects. Each entity refers to a distinct instance of a form.
 * This constant represents all of the entity types that are currently available.
 */
export const entityTypes = [
  "initiative",
  "targetPopulations",
  "evaluationPlan",
  "objectiveProgress",
] as const;

/**
 * This type is a string union type generated by the constant above.
 */
export declare type EntityType = (typeof entityTypes)[number];

export interface EntityShape {
  id: string;
  type: EntityType;
  [key: string]: any;
}

/**
 * General type for all form JSON.
 */
export interface FormJson {
  id: string;
  fields: (FormField | FormLayoutElement)[];
  heading?: AnyObject;
  options?: AnyObject;
  validation?: AnyObject;
  adminDisabled?: boolean;
  editableByAdmins?: boolean;
  verbiage?: AnyObject;
  forms?: ReportRoute[];
  initiativeId?: string;
  optional?: boolean;
  tables?: FormTable[];
}

export type FormTableRow = (string | FormField)[];
export type FormTableRows = FormTableRow[];

export interface FormTable {
  id: string;
  bodyRows: FormTableRows;
  dynamicRows?: FormTableRows;
  footRows: FormTableRows;
  headRows: FormTableRows;
  options?: AnyObject;
  tableType: FormTableType;
  verbiage?: {
    dynamicRows?: {
      buttonText: string;
      label: string;
      hint: string;
    };
    errorMessage?: string | CustomHtmlElement[];
    percentage?: string;
    title: string;
  };
}

export enum FormTableType {
  CALCULATION = "Calculation",
}

export interface CustomFieldValidation {
  type: ValidationType;
  dependentFieldName?: never;
  options?: AnyObject;
  parentOptionId?: never;
}

export interface DependentFieldValidation {
  type: string;
  dependentFieldName: string;
  options?: never;
  parentOptionId?: never;
}

export interface NestedFieldValidation {
  type: string;
  nested: true;
  options?: never;
  parentFieldName: string;
  parentOptionId: string;
}

export interface NestedDependentFieldValidation {
  type: string;
  dependentFieldName: string;
  options?: never;
  nested: true;
  parentFieldName: string;
  parentOptionId: string;
}

export type FieldValidationObject =
  | CustomFieldValidation
  | DependentFieldValidation
  | NestedFieldValidation
  | NestedDependentFieldValidation;

export interface FormField {
  id: string;
  // TODO: Convert string to ReportFormFieldType
  type: string | ReportFormFieldType;
  // TODO: Convert string to ValidationType
  validation: string | FieldValidationObject | ValidationType;
  hydrate?: string;
  props?: AnyObject;
  choices?: FieldChoice[];
  repeat?: string;
  transformation?: Transformation;
  isRequired?: boolean;
  forTableOnly?: boolean;
}

export interface Transformation {
  rule: string;
}

export function isFieldElement(
  field: FormField | FormLayoutElement
): field is FormField {
  /*
   * This function is duplicated in app-api/utils/formTemplates/formTemplates.ts
   * If you change it here, change it there!
   */
  const formLayoutElementTypes = ["sectionHeader", "sectionContent"];
  return !formLayoutElementTypes.includes(field.type);
}

export interface FormLayoutElement {
  id: string;
  type: string;
  props?: AnyObject;
  forTableOnly?: boolean;
}

export interface DropdownOptions {
  label: string;
  value: string;
}

export interface FieldChoice {
  id: string;
  name: string;
  label: string;
  value: string;
  checked?: boolean;
  children?: FormField[];
  checkedChildren?: React.ReactNode;
}

export interface ChoiceFieldProps {
  name: string;
  label: string;
  choices: FieldChoice[];
  heading?: string;
  sxOverride?: SystemStyleObject;
  [key: string]: any;
}
export interface Choice {
  key: string; // choice.name
  value: string; // choice.value
  id?: string; // choice.id
}

export interface DropdownChoice {
  label: string;
  value: string;
}

export enum ReportFormFieldType {
  CHECKBOX = "checkbox",
  DROPDOWN = "dropdown",
  DATE = "date",
  DYNAMIC = "dynamic",
  NO_TYPE = "",
  NUMBER = "number",
  RADIO = "radio",
  SECTION_HEADER = "sectionHeader",
  TEXT = "text",
  TEXTAREA = "textarea",
}
