name: 'Get status of last workflow'
description: 'Get conclusion of last workflow run on current branch.'
branding:
  icon: 'arrow-left'
  color: 'yellow'
inputs:
  github_token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  workflow_name:
    description: Name of workflow
    required: true
outputs:
  last_status:
    description: "Conclusion of last workflow run on current branch"
    value: ${{ steps.last_status.outputs.last_status }}
runs:
  using: "composite"
  steps:
    - name: Get latest workflow run ID
      id: get_workflow_run_id
      shell: bash
      run: |
        # Get the workflow runs JSON response for the specified workflow name
        WORKFLOW_RUNS=$(curl --header 'authorization: Bearer ${{ inputs.github_token }}' \
                            --header 'content-type: application/json' \
                            ${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows?workflow_name=${{ inputs.workflow_name }}| jq '.workflow_runs[0]')
        # Extract the workflow ID from the JSON response
        WORKFLOW_ID=$(echo "$WORKFLOW_RUNS" | jq -r '.id')
        echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_ENV
        echo "Workflow ID for ${{ inputs.workflow_name }}: ${WORKFLOW_ID}"
        
    - name: Get previous build status
      shell: bash
      id: last_status
      run: |
        # Validate branch name input
        if [[ ! "${{ github.event.workflow_run.head_branch }}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
          echo "Invalid branch name provided"
          exit 1
        fi
        
        # Fetch previous build status
        last_status=$(curl --silent --header 'authorization: Bearer ${{ inputs.github_token }}' \
                                    --header 'content-type: application/json' \
        "${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows/${{ env.WORKFLOW_ID }}/runs?per_page=1&status=completed&branch=${{ github.event.workflow_run.head_branch }}" \
        | jq -r .workflow_runs[0].conclusion)
        echo "last_status=$last_status" >> $GITHUB_OUTPUT
        echo "Status of the previous build: $last_status"