
npx playwright test -g "authenticate as admin"
npx playwright test -g "authenticate as user"
npx playwright test -g "Admin is accessible on all device types for admin user"
npx playwright test -g "Help is accessible on all device types for state user"
npx playwright test -g "Help is accessible on all device types for admin user"
npx playwright test -g "Should see the correct home page as a state user"
npx playwright test -g "Home is accessible on all device types for state user"
npx playwright test -g "Should see the correct home page as an admin user"
npx playwright test -g "Home is accessible on all device types for admin user"
npx playwright test -g "Is assessible when not logged in"
npx playwright test -g "Admin user can navigate to /admin"
npx playwright test -g "Profile is accessible on all device types for admin user"
npx playwright test -g "State user cannot navigate to /admin"
npx playwright test -g "Profile is accessible on all device types for state user"
npx playwright test -g "State user can create a SAR"
npx playwright test -g "Admin user can approve a Work Plan submission"
npx playwright test -g "State user can create a Work Plan"
npx playwright test -g "State user can fill and submit a Work Plan"
npx playwright test -g "Admin user can deny a work plan"
npx playwright test -g "State user can resubmit a work plan"
