name: Create main to val PR

on:
  schedule:
    - cron: "0 11 * * 1" # Every Monday at 11:00 UTC
  workflow_dispatch:
  push:
    branches:
      - bs-auto-prs

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
    - name: Set branch variables
      id: set-vars
      run: |
        echo "HEAD_BRANCH=main" >> $GITHUB_ENV
        echo "BASE_BRANCH=val" >> $GITHUB_ENV
    - name: Generate PR body
      id: pr_body
      run: |
        BODY=$(.github/commit-log.sh "$HEAD_BRANCH" "$BASE_BRANCH") || exit_code=$?
        if [ "$exit_code" == "1" ]; then
          echo "No commits. Skipping PR."
          echo "skip=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "body=$BODY" >> $GITHUB_OUTPUT
        echo "skip=false" >> $GITHUB_OUTPUT
    - name: Check if PR already exists
      if: steps.pr_body.outputs.skip != 'true'
      id: check_pr
      run: |
        PR_NUM=$(gh pr list --head "$HEAD_BRANCH" --base "$BASE_BRANCH" --json number --jq '.[0].number')
        if [ -n "$PR_NUM" ]; then
          echo "PR already exists: #$PR_NUM"
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "number=$PR_NUM" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create or update PR
      if: steps.pr_body.outputs.skip != 'true'
      run: |
        current_date=$(date '+%-d %B %Y')
        title="${HEAD_BRANCH} → ${BASE_BRANCH} (${current_date})"

        if [ "${{ steps.check_pr.outputs.exists }}" == "true" ]; then
          echo "Updating existing PR #${{ steps.check_pr.outputs.number }}"
          gh pr edit ${{ steps.check_pr.outputs.number }} \
            --title "$title" \
            --body "${{ steps.pr_body.outputs.body }}"
        else
          echo "Creating new PR"
          gh pr create \
            --head "$HEAD_BRANCH" \
            --base "$BASE_BRANCH" \
            --title "$title" \
            --body "${{ steps.pr_body.outputs.body }}" \
            --draft
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
