# This file is managed by macpro-mdct-core so if you'd like to change it let's do it there
name: Destroy

on:
  delete:
  workflow_dispatch:
    inputs:
      environment:
        description: "Name of the environment to destroy:"
        required: true

concurrency:
  group: ${{ inputs.environment || github.event.ref }}

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch' && !contains('skipci,code-json-', github.event.ref)
    steps:
      - name: Checkout repo and setup Node.js
        id: checkout-repo
        uses: ./.github/actions/checkout-repo.yml
        with:
          build-vars-names: true
          setup-node: true

      - name: Set branch-specific variable values
        run: ./.github/buildVars.sh set_values
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_OIDC_ROLE_TO_ASSUME: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}

      - name: Configure AWS credentials for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Destroy
        run: ./run destroy --stage $BRANCH_NAME --verify false
        env:
          BRANCH_NAME: ${{ steps.checkout-repo.outputs.branch_name }}

  notify_on_destroy_failure:
    runs-on: ubuntu-latest
    needs:
      - destroy
    if: ${{ failure() }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ":boom: A destroy action has failed on ${{ github.repository }}."
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.INTEGRATIONS_SLACK_WEBHOOK }}
