# This file is managed by macpro-mdct-core so if you'd like to change it let's do it there
name: gitleaks

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  setup:
    name: Checkout repo
    uses: ./.github/workflows/checkout-repo.yml

  gitleaks-scan:
    name: Gitleaks scan
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Gitleaks scan
        uses: docker://zricethezav/gitleaks:v8.24.3
        with:
          args: detect --source /github/workspace/ --no-git --verbose
