# This file is managed by macpro-mdct-core so if you'd like to change it let's do it there
name: Pull Request

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  prchecks:
    name: prchecks 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js for pre-commit
        uses: actions/setup-node@v5.0.0
        with:
          node-version-file: ".nvmrc"

      - name: Setup Python for pre-commit
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Configure pre-commit to skip some validations
        run: |
          echo "SKIP=branch-name-validation,typescript-check,typescript-check-api,typescript-check-ui" >> $GITHUB_ENV
      - uses: pre-commit/action@v3.0.1

  assignAuthor:
    name: assignAuthor
    if: github.event.pull_request.user.type != 'Bot' && github.event.action != 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to creator
        run: gh pr edit $PR_URL --add-assignee $PR_AUTHOR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{github.event.pull_request.html_url}}
