# This file is managed by macpro-mdct-core so if you'd like to change it let's do it there
name: Pull Request

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  prchecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: checkout-repo
        uses: ./.github/actions/checkout-repo.yml

      - name: Setup Python for pre-commit
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Configure pre-commit to skip some validations
        run: |
          echo "SKIP=branch-name-validation,typescript-check,typescript-check-api,typescript-check-ui" >> $GITHUB_ENV
      - uses: pre-commit/action@v3.0.1

  assignAuthor:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.type != 'Bot'
    steps:
      - name: Checkout repo
        id: checkout-repo
        uses: ./.github/actions/checkout-repo.yml

      - name: Assign PR to Creator
        run: |
          gh pr edit $PR_NUM --add-assignee $PR_AUTHOR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
