# This file is managed by macpro-mdct-core so if you'd like to change it let's do it there
name: Update Code.json
on:
  schedule:
    # monthly on day 1
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  setup:
    name: Checkout repo (full history) and setup Node.js
    uses: ./.github/workflows/checkout-repo.yml
    with:
      fetch-depth: 0
      setup-node: true

  update-code-json:
    name: Update code.json
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version: "1.22"

      - name: Install SCC
        run: go install github.com/boyter/scc/v3@v3.5.0

      - name: Update code.json
        uses: DSACMS/automated-codejson-generator@main
        with:
          BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
